### ISSUE TITLE
Update hex file for motion sensor revision

### ISSUE THREAD

**Issue by microbit-mark** [Louismac/CBMicroBit#3]
The hex needs to be recompiled for use with micro:bits that use a combined accelerometer and magnetometer https://support.microbit.org/a/solutions/articles/19000087023-micro-bit-motion-sensor-hardware-changes-for-content-authors

**Comment by Louismac** [comment]
Hi 
I built the hex with the lancaster university examples and yotta. If I pull their most recent code and rebuild using that pipeline, will it work with the updated sensors?

**Comment by themarkness** [comment]
Yep. That would be awesome. Thanks
